source 'http://rubygems.org'

gem 'rails', '3.0.5'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# gem 'sqlite3'

gem 'devise'
gem 'rakismet'
gem 'thinking-sphinx', '2.0.0', :require => 'thinking_sphinx'
gem 'governor', '>= 0.2.2'
gem 'governor_thinking_sphinx', :path => '../..'

gem 'dynamic_form'

gem 'will_paginate', '~> 3.0.beta'

group :development do
  gem 'mysql2'
end